path=/content/wknd/us/en/training-search
type=cq:Page
property=jcr:content/cq:tags
property.value=training:activity/hiking
orderby=@jcr:content/jcr:title
orderby.sort=asc
p.limit=2
p.offset=0
p.guessTotal=true
